### ISSUE TITLE
Compilation error on python download

### ISSUE THREAD

**Issue by Astalaseven** [fw4spl-org/fw4spl-deps#1]
Hi,

Should it be possible to take the download of python out of the compilation process as it is already installed through the [prerequisites](http://fw4spl-doc.readthedocs.org/en/fw4spl_0.10.1/Installation/src/LinuxInstall.html)?

```
[ 19%] Performing download step (download, verify and extract) for 'python'
-- downloading...
     src='http://www.python.org/ftp/python/2.7.8/Python-2.7.8.tgz'
     dst='/home/asta/FW4SPL/BinPkgs/fw4spl-deps/archive/Python-2.7.8.tgz'
     timeout='none'
CMake Error at python-stamp/download-python.cmake:21 (message):
  error: downloading
  'http://www.python.org/ftp/python/2.7.8/Python-2.7.8.tgz' failed

    status_code: 1
    status_string: "Unsupported protocol"
    log: Hostname was NOT found in DNS cache
    Trying 185.31.18.223...

  Connected to www.python.org (185.31.18.223) port 80 (#0)

  GET /ftp/python/2.7.8/Python-2.7.8.tgz HTTP/1.1

  User-Agent: curl/7.38.0

  Host: www.python.org

  Accept: */*



  HTTP/1.1 301 Moved Permanently

  Server Varnish is not blacklisted

  Server: Varnish

  Retry-After: 0

  Location: https://www.python.org/ftp/python/2.7.8/Python-2.7.8.tgz

  Content-Length: 0

  Accept-Ranges: bytes

  Date: Thu, 16 Jul 2015 11:45:34 GMT

  Via: 1.1 varnish

  Connection: close

  X-Served-By: cache-lcy1125-LCY

  X-Cache: HIT

  X-Cache-Hits: 0

  Public-Key-Pins: max-age=600; includeSubDomains;
  pin-sha256="WoiWRyIOVNa9ihaBciRSC7XHjliYS9VwUGOIud4PB18=";
  pin-sha256="5C8kvU039KouVrl52D0eZSGf4Onjo4Khs8tmyTlV3nU=";
  pin-sha256="5C8kvU039KouVrl52D0eZSGf4Onjo4Khs8tmyTlV3nU=";
  pin-sha256="lCppFqbkrlJ3EcVFAkeip0+44VaoJUymbnOaEUk7tEU=";
  pin-sha256="TUDnr0MEoJ3of7+YliBMBVFB4/gJsv5zO7IxD9+YoWI=";
  pin-sha256="x4QzPSC810K5/cMjb05Qm4k3Bw5zBn4lTdO/nEW/Td4=";

  Strict-Transport-Security: max-age=63072000; includeSubDomains



  Closing connection 0

  Issue another request to this URL:
  'https://www.python.org/ftp/python/2.7.8/Python-2.7.8.tgz'

  Protocol "https" not supported or disabled in libcurl

  Closing connection -1

make[2]: *** [python/python-prefix/src/python-stamp/python-download] Erreur 1
make[1]: *** [python/CMakeFiles/python.dir/all] Erreur 2
make: *** [all] Erreur 2
```

**Comment by FredChamp** [comment]
I'm not sure but @greenjava told me that could be the problem:

_http://www.cmake.org/pipermail/cmake/2010-December/041295.html_

"**CMake builds its own curl, without ssl support by default**, unless you
point it to the system curl.

You can rebuild CMake with the **CMAKE_USE_OPENSSL ON** if you have all
the right supporting system libraries installed."

**Comment by Astalaseven** [comment]
If I remember well `curl` is build after `python`, so I add to build it myself or download the `tar` so the installer skip the download :)

**Comment by fbridault** [comment]
This has nothing to do with our version curl, this has to do with the version of cmake you used. Probably, you compiled it yourself and forgot to compile it with curl support. As stated in the latest documentation (that was not the case when you tried ofc, but I mention it for future reference) http://fw4spl.readthedocs.io/en/fw4spl_0.11.0/Installation/src/LinuxInstall.html#prerequisites-for-linux-users, it is recommended to use the binary builds of cmake.
