### ISSUE TITLE
Numpy cannot be downloaded

### ISSUE THREAD

**Issue by Astalaseven** [fw4spl-org/fw4spl-deps#3]
The url is invalid, correct one is: 
`http://ufpr.dl.sourceforge.net/project/numpy/NumPy/1.9.1/numpy-1.9.1.tar.gz`
and not:
`http://sourceforge.net/projects/numpy/files/NumPy/1.9.1/numpy-1.9.1.tar.gz/download`

**Comment by FredChamp** [comment]
Thanks !
We do not often compile or use Numpy but indeed the url is invalid. We will submit the change as soon as we have tested it on each platforms ( Window , Linux, OSX)

**Comment by fbridault** [comment]
Numpy moved to fw4spl-ext-deps and should compile now. Anyway it is no longer needed as a core dependency.
